### ISSUE TITLE
Passive Buzzer Speaker is unavailable on Amazon

### ISSUE THREAD

**Issue by GaloisGirl** [mytechnotalent/Python-For-Kids#2]
The speaker at https://www.amazon.com/Passive-Buzzer-Speaker-Arduino-Raspberry/dp/B085XQM69Z/ is unavailable on Amazon. Consider adding an alternative link.

**Comment by mytechnotalent** [comment]
@GaloisGirl Thank you Anna that is a great idea and I will add a "what you need" doc as well.
