### ISSUE TITLE
The links in the LinkedIn articles are not clickable

### ISSUE THREAD

**Issue by GaloisGirl** [mytechnotalent/Python-For-Kids#4]
This is bad UX, but more importantly, an accessibility problem.

**Comment by mytechnotalent** [comment]
Hi @GaloisGirl when you click on the HERE it does open the page as I just tested it on three machines.

**Comment by mytechnotalent** [comment]
Oh I see now you mean within the articles.  I will try to fix that now.

**Comment by mytechnotalent** [comment]
The Amazon links LinkedIn will not allow so I made note.  The microbit.com works however thank you again Anna!
