### ISSUE TITLE
Any reason for the ref params in the links?

### ISSUE THREAD

**Issue by GaloisGirl** [mytechnotalent/Python-For-Kids#5]
Any reason for the ref params in the links to Amazon?

**Comment by mytechnotalent** [comment]
The intent was to provide an easy way to have someone find and obtain the device.

**Comment by GaloisGirl** [comment]
I meant the tracking part of the URLs.  Take the first product: `https://www.amazon.com/gp/product/B01G8X7VM2/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1` 

You could just link `https://www.amazon.com/gp/product/B01G8X7VM2/` .

The second part is for [URL tracking](https://dashthis.com/blog/how-url-tracking-works/), and tracking children is problematic.

**Comment by mytechnotalent** [comment]
Thank you I will fix this now.
