### ISSUE TITLE
Can I work on program to with wait and delay ?

### ISSUE THREAD

**Issue by yashvarshney003** [mytechnotalent/Python-For-Kids#6]
Means with command wait and delay.

**Comment by mytechnotalent** [comment]
Hi @yashvarshney003 you would do the following in the REPL.
`import utime`
`utime.sleep(1)`

Where 1 represents waiting a second you can change to any value you like.

Here is the docs: https://minipython.readthedocs.io/en/latest/utime.html

**Comment by yashvarshney003** [comment]
Can I contribute by making a program demonstrating delay for repo??

**Comment by mytechnotalent** [comment]
Hi @yashvarshney003 this tutorial series is very specific and limited in its scope however if you would be interested I have my own fork of the original BBC MicroPython port called MiniPython.  Would you like to submit a PR to the master branch for an example program which I can review?  [MiniPython REPO](https://github.com/mytechnotalent/minipython)

**Comment by yashvarshney003** [comment]
ok.
